name: War
version: ${project.version}
description: ${project.description}
author: cmastudios
website: ${project.url}
main: ${main.class}
commands: {}
permissions:
  war.teleport:
    description: Required to teleport to a warzone
    default: true
  war.zonemaker:
    description: Required to modify and set warzones
    children:
      war.zone.create: true
      war.zone.delete: true
      war.zone.config: true
      war.zone.save: true
      war.zone.reset: true
      war.zone.construct: true
  war.config:
    description: Change global War config